name: Progress report

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * 1"
      timezone: "Europe/Moscow"

permissions:
  contents: read
  pull-requests: read

jobs:
  report:
    name: Course progress
    uses: web-programming-contest/web-programming-ci-utils/.github/workflows/progress-report.yml@5d95c7682c0557242b6d4835a402d9e65b2cf829
    with:
      utils_repository: web-programming-contest/web-programming-ci-utils
      utils_ref: "5d95c7682c0557242b6d4835a402d9e65b2cf829"
