name: Submission

on:
  pull_request_target:
    branches: [master]
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: read

jobs:
  submission:
    name: Automated submission checks
    uses: web-programming-contest/web-programming-ci-utils/.github/workflows/submission.yml@5807ddc58c37f716214c5139b3ec0d20b7ed0f34
    with:
      utils_repository: web-programming-contest/web-programming-ci-utils
      utils_ref: "5807ddc58c37f716214c5139b3ec0d20b7ed0f34"
