name: Submission

on:
  pull_request_target:
    branches: [master]
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: read

jobs:
  submission:
    name: Automated submission checks
    uses: web-programming-contest/web-programming-ci-utils/.github/workflows/submission.yml@3c430e6efc9f812519b568ca796e13cc0d481cab
    with:
      utils_repository: web-programming-contest/web-programming-ci-utils
      utils_ref: "3c430e6efc9f812519b568ca796e13cc0d481cab"
